<?php

namespace Henter\GEOBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PlaceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Henter\GEOBundle\Controller\PlaceController();
        return $instance;
    }
}
