<?php

namespace Henter\GEOBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BaseController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Henter\GEOBundle\Controller\BaseController();
        return $instance;
    }
}
